title: "💡 Feature request"
labels: ["feature request"]
body:
  - type: checkboxes
    id: search_discussions
    attributes:
      label: Is there an existing discussion for this?
      description: Please search to see if a discussion already exists for the feature you are requesting. (https://github.com/masterking32/MasterCryptoFarmBot/discussions).
      options:
        - label: I have searched the existing discussions
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe the problem.
      description: A clear and concise description of what the problem is.
      placeholder: I am trying to do [...] but [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen. Include any alternative solutions you've considered.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: |
        Add any other context about alternative solutions you've considered.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
